--CREATE DATABASE IF NOT EXISTS `paymybuddy`;
--USE `paymybuddy`;
--CREATE TABLE IF NOT EXISTS `user` (
--  `id` BIGINT NOT NULL AUTO_INCREMENT,
--  `firstname` VARCHAR(50) NOT NULL,
--  `lastname` VARCHAR(50) NOT NULL,
--  `username` VARCHAR(50) NOT NULL,
--  `email` VARCHAR(255) NOT NULL,
--  `password` VARCHAR(255) NOT NULL,
--  `balance` DECIMAL(18,2) NOT NULL,
--  `bankaccountnumber` varchar(255) NOT NULL,
--    `amount` decimal(10,2) NOT NULL,
--  PRIMARY KEY (`id`),
--  UNIQUE INDEX `email` (`email` ASC) VISIBLE);
